using MassTransit;
using Microsoft.Extensions.Logging;
using NotificationService.Domain.Entities;
using NotificationService.Domain.Interfaces;
using ServiceContracts;

namespace NotificationService.App.Features.Consumer
{
    public class PaymentSucceededConsumer : IConsumer<PaymentSucceededEvent>
    {
        private readonly ILogger<PaymentSucceededConsumer> _logger;
        private readonly INotificationRepository _notificationRepository;

        public PaymentSucceededConsumer(ILogger<PaymentSucceededConsumer> logger, INotificationRepository notificationRepository)
        {
            _logger = logger;
            _notificationRepository = notificationRepository;
        }
        public async Task Consume(ConsumeContext<PaymentSucceededEvent> context)
        {
            if (context == null || context.Message == null)
            {
                _logger.LogWarning("Received null context or message in PaymentSucceededConsumer.");
                throw new ArgumentNullException(nameof(context));
            }

            _logger.LogInformation("Received PaymentSucceededEvent for OrderId: {OrderId}, PaymentId: {PaymentId}, Amount: {Amount}, Timestamp: {Timestamp}",
                context.Message.OrderId, context.Message.PaymentId, context.Message.Amount, context.Message.Timestamp);

            var message = context.Message;

            var notification = new Notification
            {
                Id = new Random().Next(1, 1000), // Just for demonstration in real scenario, it should be generated by the database
                OrderId = message.OrderId,
                PaymentId = message.PaymentId,
                Amount = message.Amount,
                Timestamp = message.Timestamp,
            };
            await _notificationRepository.CreateNotificationAsync(notification, context.CancellationToken);
            _logger.LogInformation("Notification created for OrderId: {OrderId}, PaymentId: {PaymentId}", notification.OrderId, notification.PaymentId);
        }
    }
}
